'use server'
import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'

export async function createAppointment(orderId, date, time, purpose='OR Presentation & Item Pickup') {
  const supabase = await createClient()
  
  // 1. Get current user
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, message: 'Unauthorized' }

  // 2. Get profile
  const { data: profile } = await supabase
    .from('users')
    .select('user_id')
    .eq('auth_id', user.id)
    .single()

  if (!profile) return { success: false, message: 'Profile not found' }

  try {
    // 3. Create Appointment
    const { data: appt, error } = await supabase
      .from('appointments')
      .insert({
        user_id: profile.user_id,
        order_id: orderId,
        schedule_date: date,
        time_slot: time,
        purpose: purpose,
        status: 'Confirmed'
        // appt_number is auto-generated by trigger
      })
      .select()
      .single()

    if (error) throw error

    revalidatePath('/shop/profile')
    return { success: true, appointment: appt }

  } catch (error) {
    console.error('Appointment creation failed:', error)
    return { success: false, message: 'Failed to book appointment. Please try again.' }
  }
}
