'use server'
import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'

export async function createOrder(cartItems, totalAmount) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, message: 'You must be logged in to place an order.' }

  const { data: profile } = await supabase
    .from('users').select('user_id').eq('auth_id', user.id).single()
  if (!profile) return { success: false, message: 'User profile not found.' }

  try {
    // Insert order — order_number is generated by DB trigger
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        user_id: profile.user_id,
        total_amount: totalAmount,
        status: 'Pending',
      })
      .select('order_id, order_number')
      .single()

    if (orderError) throw orderError

    // Insert order items
    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(cartItems.map(item => ({
        order_id: order.order_id,
        item_id: item.item_id,
        quantity: item.quantity,
        unit_price: item.price,
      })))

    if (itemsError) throw itemsError

    // Update reserved_quantity for each item — try rpc, fall back to direct update
    for (const item of cartItems) {
      const { error: rpcError } = await supabase.rpc('increment_reserved', {
        p_item_id: item.item_id,
        p_qty: item.quantity,
      })

      // If rpc doesn't exist, do a direct increment instead
      if (rpcError) {
        const { data: current } = await supabase
          .from('bookstore_items')
          .select('reserved_quantity')
          .eq('item_id', item.item_id)
          .single()

        if (current) {
          await supabase
            .from('bookstore_items')
            .update({ reserved_quantity: current.reserved_quantity + item.quantity })
            .eq('item_id', item.item_id)
        }
      }
    }

    revalidatePath('/shop')
    return { success: true, orderId: order.order_id, orderNumber: order.order_number }

  } catch (error) {
    console.error('Order creation failed:', error)
    return { success: false, message: error.message || 'Failed to place order. Please try again.' }
  }
}