'use server'
import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'

export async function createOrder(cartItems, totalAmount) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, message: 'You must be logged in to place an order.' }

  const { data: profile } = await supabase
    .from('users').select('user_id').eq('auth_id', user.id).single()
  if (!profile) return { success: false, message: 'User profile not found.' }

  try {
    // Insert order — do NOT pass order_number, the DB trigger generates it
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        user_id: profile.user_id,
        total_amount: totalAmount,
        status: 'Pending',
        // order_number intentionally omitted — generated by trg_order_number trigger
      })
      .select('order_id, order_number')
      .single()

    if (orderError) throw orderError

    // Insert order items
    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(cartItems.map(item => ({
        order_id: order.order_id,
        item_id: item.item_id,
        quantity: item.quantity,
        unit_price: item.price,
      })))

    if (itemsError) throw itemsError

    // Update reserved_quantity for each item
    for (const item of cartItems) {
      await supabase.rpc('increment_reserved', {
        p_item_id: item.item_id,
        p_qty: item.quantity,
      }).catch(() => {
        // rpc may not exist — fallback: direct update
        supabase
          .from('bookstore_items')
          .select('reserved_quantity')
          .eq('item_id', item.item_id)
          .single()
          .then(({ data }) => {
            if (data) {
              supabase.from('bookstore_items')
                .update({ reserved_quantity: data.reserved_quantity + item.quantity })
                .eq('item_id', item.item_id)
            }
          })
      })
    }

    // DO NOT auto-create a payment record here.
    // Payments are only recorded when cash/OR is actually received by staff.
    // For <₱100: staff records Bookstore payment when student pays at counter.
    // For ≥₱100: staff records Teller payment after student presents OR.

    revalidatePath('/shop')
    return { success: true, orderId: order.order_id, orderNumber: order.order_number }

  } catch (error) {
    console.error('Order creation failed:', error)
    return { success: false, message: error.message || 'Failed to place order. Please try again.' }
  }
}