'use server'
import { createClient } from '@/lib/db/server'
import { revalidatePath } from 'next/cache'

export async function createOrder(cartItems, totalAmount) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, message: 'You must be logged in to place an order.' }

  const { data: profile } = await supabase
    .from('users').select('id_number').eq('auth_id', user.id).single()
  if (!profile) return { success: false, message: 'User profile not found.' }

  try {
    // Validate stock availability before creating the order
    const itemIds = [...new Set(cartItems.map(i => i.item_id))]
    const { data: stockData, error: stockErr } = await supabase
      .from('bookstore_items')
      .select('item_id, name, stock_quantity, reserved_quantity')
      .in('item_id', itemIds)

    if (stockErr) throw stockErr

    const stockMap = Object.fromEntries((stockData || []).map(s => [s.item_id, s]))
    const outOfStock = []

    for (const item of cartItems) {
      const stock = stockMap[item.item_id]
      if (!stock) {
        outOfStock.push(`"${item.name}" is no longer available.`)
        continue
      }
      const available = stock.stock_quantity - (stock.reserved_quantity || 0)
      if (available < item.quantity) {
        outOfStock.push(
          available <= 0
            ? `"${stock.name}" is out of stock.`
            : `"${stock.name}" only has ${available} available (you requested ${item.quantity}).`
        )
      }
    }

    if (outOfStock.length > 0) {
      return { success: false, message: outOfStock.join(' ') }
    }

    // Insert order — order_number is generated by DB trigger
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        user_id: profile.id_number,
        total_amount: totalAmount,
        status: 'Pending',
      })
      .select('order_id, order_number')
      .single()

    if (orderError) throw orderError

    // Insert order items
    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(cartItems.map(item => ({
        order_id: order.order_id,
        item_id: item.item_id,
        quantity: item.quantity,
        unit_price: item.price,
        ...(item.selectedSize ? { size: item.selectedSize } : {}),
      })))

    if (itemsError) throw itemsError

    // Update reserved_quantity for each item — try rpc, fall back to direct update
    for (const item of cartItems) {
      const { error: rpcError } = await supabase.rpc('increment_reserved', {
        p_item_id: item.item_id,
        p_qty: item.quantity,
      })

      // If rpc doesn't exist, do a direct increment instead
      if (rpcError) {
        const { data: current } = await supabase
          .from('bookstore_items')
          .select('reserved_quantity')
          .eq('item_id', item.item_id)
          .single()

        if (current) {
          await supabase
            .from('bookstore_items')
            .update({ reserved_quantity: current.reserved_quantity + item.quantity })
            .eq('item_id', item.item_id)
        }
      }
    }

    // Notify the customer with realistic next-step guidance
    const paymentNote = totalAmount >= 100
      ? 'Please pay at the University Teller and present the Official Receipt at the Bookstore.'
      : 'Visit the Bookstore to pay and pick up your items.'
    await supabase.from('notifications').insert({ user_id: profile.id_number, title: 'Order Slip Created', message: `Your order #${order.order_number} has been placed. Total: ₱${totalAmount.toFixed(2)}. ${paymentNote}`, type: 'info', reference_type: 'order', reference_id: order.order_id })

    revalidatePath('/shop')
    return { success: true, orderId: order.order_id, orderNumber: order.order_number }

  } catch (error) {
    console.error('Order creation failed:', error)
    return { success: false, message: error.message || 'Failed to place order. Please try again.' }
  }
}